# cloudflared
- name: Install cloudflared
  get_url:
    url: "{{ cloudflared_download_url }}"
    dest: /usr/local/bin/cloudflared
    mode: +x

- name: Create cloudflared config
  copy:
    dest: /etc/cloudflared/config.yml
    content: |
      proxy-dns: true
      proxy-dns-port: {{ cloudflared_port }}
      proxy-dns-upstream:
        - https://1.1.1.1/dns-query
        - https://1.0.0.1/dns-query

- name: Get existing services
  service_facts:

- name: Install cloudflared service
  command:
    cmd: cloudflared service install --legacy
  when: "'cloudflared.service' not in ansible_facts.services"

- name: Start cloudflared service
  service:
    name: cloudflared
    state: started
    enabled: yes

- name: Start cloudflared update timer
  service:
    name: cloudflared-update.timer
    state: started
    enabled: yes
