- name: Update packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install essential packages
  package:
    name:
      - python3
      - python3-pip
      - vim
      - neofetch
      - htop
    state: latest

- name: Get installed packages as facts
  package_facts:
    manager: auto

# install docker
- name: Get Docker installer
  uri:
    url: https://get.docker.com
    return_content: yes
  register: docker_installer
  when: "'docker-ce' not in ansible_facts.packages"

- name: Install Docker
  shell:
    cmd: sh
    stdin: "{{ docker_installer.content }}"
  when: "'docker-ce' not in ansible_facts.packages"
###

- name: Disable SSH password auth
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: Enable passwordless sudo for "{{ username }}"
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Restart SSH daemon
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed
