- name: Update packages
  apt:
    update_cache: yes
    upgrade: yes
  tags: essential

- name: Turn off wifi power saver
  lineinfile:
    path: /etc/rc.local
    insertbefore: exit 0
    line: /sbin/iwconfig wlan0 power off
  tags: essential
