- name: Pull healthchecks image
  docker_image:
    name: lscr.io/linuxserver/healthchecks:latest
    source: pull
    timeout: 300
  tags: healthchecks

- name: Init healthchecks
  docker_container:
    name: healthchecks
    image: lscr.io/linuxserver/healthchecks:latest
    dns_servers:
      - "{{ pihole_subnet_ip }}"
    state: started
    env:
      PUID: "{{ puid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
      SITE_ROOT: "https://healthchecks.{{ domain_name }}"
      SITE_NAME: "HealthChecks"
      DEFAULT_FROM_EMAIL: "{{ smtp_email }}"
      EMAIL_HOST: "{{ smtp_host }}"
      EMAIL_PORT: "{{ smtp_port }}"
      EMAIL_HOST_USER: "{{ smtp_email }}"
      EMAIL_HOST_PASSWORD: "{{ smtp_app_password }}"
      EMAIL_USE_TLS: "False"
      SUPERUSER_EMAIL: "{{ email }}"
      SUPERUSER_PASSWORD: "{{ healthchecks_password }}"
    volumes:
      - /etc/healthchecks/config:/config
    restart_policy: unless-stopped
    networks:
      - name: "{{ subnet_name }}"
        ipv4_address: "{{ healthchecks_subnet_ip }}"
  tags: healthchecks

- name: Enable healthchecks upstream in swag
  copy:
    src: /etc/swag/config/nginx/proxy-confs/healthchecks.subdomain.conf.sample
    dest: /etc/swag/config/nginx/proxy-confs/healthchecks.subdomain.conf
    remote_src: yes
    force: no
  notify: Restart swag
  tags: healthchecks

- name: Block external ips
  replace:
    path: /etc/swag/config/nginx/proxy-confs/healthchecks.subdomain.conf
    regexp: '^(?: *include /config/nginx/internal\.conf;\n)?( *include /config/nginx/proxy\.conf;\n)'
    replace: '        include /config/nginx/internal.conf;\n\1'
  notify: Restart swag
  tags: healthchecks
