- name: Pull jackett image
  docker_image:
    name: lscr.io/linuxserver/jackett
    source: pull
    timeout: 300
  tags: jackett

- name: Init jackett
  docker_container:
    name: jackett
    image: lscr.io/linuxserver/jackett
    dns_servers:
      - 1.1.1.1
    state: started
    env:
      PUID: "{{ puid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
      AUTO_UPDATE: "false"
    volumes:
      - /etc/jackett/config:/config
      - "{{ data_dir }}/Downloads:/downloads"
    sysctls:
      net.ipv6.conf.all.disable_ipv6: "1"
    restart_policy: unless-stopped
    networks:
      - name: "{{ subnet_name }}"
        ipv4_address: "{{ jackett_subnet_ip }}"
  tags: jackett

- name: Enable jackett upstream in swag
  copy:
    src: /etc/swag/config/nginx/proxy-confs/jackett.subdomain.conf.sample
    dest: /etc/swag/config/nginx/proxy-confs/jackett.subdomain.conf
    remote_src: yes
    force: no
  notify: Restart swag
  tags: jackett

- name: Add cors config
  replace:
    path: /etc/swag/config/nginx/proxy-confs/jackett.subdomain.conf
    regexp: '^(?: *include /config/nginx/cors\.conf;\n)?( *include /config/nginx/proxy\.conf;\n)'
    replace: '        include /config/nginx/cors.conf;\n\1'
  notify: Restart swag
  tags: jackett

- name: Block external ips
  replace:
    path: /etc/swag/config/nginx/proxy-confs/jackett.subdomain.conf
    regexp: '^(?: *include /config/nginx/internal\.conf;\n)?( *include /config/nginx/cors\.conf;\n)'
    replace: '        include /config/nginx/internal.conf;\n\1'
  notify: Restart swag
  tags: jackett
