- name: Pull lidarr image
  docker_image:
    name: lscr.io/linuxserver/lidarr
    source: pull
    timeout: 300
  tags: lidarr

- name: Init lidarr
  docker_container:
    name: lidarr
    image: lscr.io/linuxserver/lidarr
    dns_servers:
      - "{{ pihole_subnet_ip }}"
    state: started
    env:
      PUID: "{{ puid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
    volumes:
      - /etc/lidarr/config:/config
      - "{{ data_dir }}/Documents/Music:/music"
      - "{{ data_dir }}/Downloads:/downloads"
    restart_policy: unless-stopped
    networks:
      - name: "{{ subnet_name }}"
        ipv4_address: "{{ lidarr_subnet_ip }}"
  tags: lidarr

- name: Enable lidarr upstream in swag
  copy:
    src: /etc/swag/config/nginx/proxy-confs/lidarr.subdomain.conf.sample
    dest: /etc/swag/config/nginx/proxy-confs/lidarr.subdomain.conf
    remote_src: yes
    force: no
  notify: Restart swag
  tags: lidarr

- name: Block external ips
  replace:
    path: /etc/swag/config/nginx/proxy-confs/lidarr.subdomain.conf
    regexp: '^(?: *include /config/nginx/internal\.conf;\n)?( *include /config/nginx/proxy\.conf;\n)'
    replace: '        include /config/nginx/internal.conf;\n\1'
  notify: Restart swag
  tags: lidarr
