- name: Pull mariadb image
  docker_image:
    name: lscr.io/linuxserver/mariadb
    source: pull
    timeout: 300
  tags: nextcloud

- name: Init MariaDB
  docker_container:
    name: nextcloud-mariadb
    image: lscr.io/linuxserver/mariadb
    dns_servers:
      - "{{ pihole_subnet_ip }}"
    state: started
    env:
      PUID: "{{ puid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
      MYSQL_ROOT_PASSWORD: "{{ nextcloud_mariadb_root_password }}"
      MYSQL_PASSWORD: "{{ nextcloud_mariadb_password }}"
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
    volumes:
      - "{{ data_dir }}/Applications/nextcloud_mariadb/config:/config"
    restart_policy: unless-stopped
    networks:
      - name: "{{ subnet_name }}"
        ipv4_address: "{{ nextcloud_mariadb_subnet_ip }}"
  tags: nextcloud

- name: Pull nextcloud image
  docker_image:
    name: lscr.io/linuxserver/nextcloud
    source: pull
    timeout: 300
  tags: nextcloud

- name: Init nextcloud
  docker_container:
    name: nextcloud
    image: lscr.io/linuxserver/nextcloud
    dns_servers:
      - "{{ pihole_subnet_ip }}"
    state: started
    env:
      PUID: "{{ puid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ data_dir }}/Applications/nextcloud/config:/config"
      - "{{ data_dir }}/Documents/Cloud:/data"
      - "{{ data_dir }}/Documents/Photos:/shared/photos"
      - "{{ data_dir }}/Documents/Movies:/shared/movies"
      - "{{ data_dir }}/Documents/TV:/shared/tv"
      - "{{ data_dir }}/Documents/Music:/shared/music"
      - "{{ data_dir }}/Documents/Books:/shared/books"
    restart_policy: unless-stopped
    networks:
      - name: "{{ subnet_name }}"
        ipv4_address: "{{ nextcloud_subnet_ip }}"
  tags: nextcloud

- name: Enable nextcloud upstream in swag
  copy:
    src: /etc/swag/config/nginx/proxy-confs/nextcloud.subdomain.conf.sample
    dest: /etc/swag/config/nginx/proxy-confs/nextcloud.subdomain.conf
    remote_src: yes
    force: no
  notify: Restart swag
  tags: nextcloud
