- name: Pull cloudflared image
  docker_image:
    name: crazymax/cloudflared:latest
    source: pull
    timeout: 300
  tags: pihole

- name: Init cloudflared
  docker_container:
    name: cloudflared
    image: crazymax/cloudflared:latest
    state: started
    env:
      TZ: "{{ timezone }}"
    restart_policy: unless-stopped
    networks:
      - name: "{{ subnet_name }}"
        ipv4_address: "{{ cloudflared_subnet_ip }}"
  tags: pihole

- name: Pull pihole image
  docker_image:
    name: pihole/pihole:latest
    source: pull
    timeout: 300
  tags: pihole

- name: Init pihole
  docker_container:
    name: pihole
    image: pihole/pihole:latest
    dns_servers:
      - 127.0.0.1
      - 8.8.8.8
    capabilities:
      - net_admin
    state: started
    env:
      TZ: "{{ timezone }}"
      WEBPASSWORD: "{{ pihole_password }}"
      IPv6: "false"
      DNS1: "{{ cloudflared_subnet_ip }}#5053"
      DNS2: "no"
      CORS_HOSTS: "homer.{{ domain_name }},homer.lan"
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - "/etc/pihole:/etc/pihole"
      - "/etc/dnsmasq.d:/etc/dnsmasq.d"
    restart_policy: unless-stopped
    networks:
      - name: "{{ subnet_name }}"
        ipv4_address: "{{ pihole_subnet_ip }}"
  tags: pihole

- name: Enable pihole upstream in swag
  copy:
    src: /etc/swag/config/nginx/proxy-confs/pihole.subdomain.conf.sample
    dest: /etc/swag/config/nginx/proxy-confs/pihole.subdomain.conf
    remote_src: yes
    force: no
  notify: Restart swag
  tags: pihole

- name: Block external ips
  replace:
    path: /etc/swag/config/nginx/proxy-confs/pihole.subdomain.conf
    regexp: '^(?: *include /config/nginx/internal\.conf;\n)?( *include /config/nginx/proxy\.conf;\n)'
    replace: '        include /config/nginx/internal.conf;\n\1'
  notify: Restart swag
  tags: pihole
