- name: Pull portainer image
  docker_image:
    name: portainer/portainer-ce:latest
    source: pull
    timeout: 300
  tags: portainer

- name: Init portainer
  docker_container:
    name: portainer
    image: portainer/portainer-ce:latest
    dns_servers:
      - "{{ pihole_subnet_ip }}"
    state: started
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/portainer/data:/data
    restart_policy: unless-stopped
    networks:
      - name: "{{ subnet_name }}"
        ipv4_address: "{{ portainer_subnet_ip }}"
  tags: portainer

- name: Enable portainer upstream in swag
  copy:
    src: /etc/swag/config/nginx/proxy-confs/portainer.subdomain.conf.sample
    dest: /etc/swag/config/nginx/proxy-confs/portainer.subdomain.conf
    remote_src: yes
    force: no
  notify: Restart swag
  tags: portainer

- name: Block external ips
  replace:
    path: /etc/swag/config/nginx/proxy-confs/portainer.subdomain.conf
    regexp: '^(?: *include /config/nginx/internal\.conf;\n)?( *include /config/nginx/proxy\.conf;\n)'
    replace: '        include /config/nginx/internal.conf;\n\1'
  notify: Restart swag
  tags: portainer
