- name: Pull readarr image
  docker_image:
    name: lscr.io/linuxserver/readarr:develop
    source: pull
    timeout: 300
  tags: readarr

- name: Init readarr
  docker_container:
    name: readarr
    image: lscr.io/linuxserver/readarr:develop
    dns_servers:
      - 1.1.1.1
    state: started
    env:
      PUID: "{{ puid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
    volumes:
      - /etc/readarr/config:/config
      - "{{ data_dir }}/Documents/Books:/books"
      - "{{ data_dir }}/Downloads:/downloads"
    restart_policy: unless-stopped
    networks:
      - name: "{{ subnet_name }}"
        ipv4_address: "{{ readarr_subnet_ip }}"
  tags: readarr

- name: Enable readarr upstream in swag
  copy:
    src: /etc/swag/config/nginx/proxy-confs/readarr.subdomain.conf.sample
    dest: /etc/swag/config/nginx/proxy-confs/readarr.subdomain.conf
    remote_src: yes
    force: no
  notify: Restart swag
  tags: readarr

- name: Block external ips
  replace:
    path: /etc/swag/config/nginx/proxy-confs/readarr.subdomain.conf
    regexp: '^(?: *include /config/nginx/internal\.conf;\n)?( *include /config/nginx/cors\.conf;\n)'
    replace: '        include /config/nginx/internal.conf;\n\1'
  notify: Restart swag
  tags: readarr
