- name: Get installed packages as facts
  package_facts:
    manager: auto

- name: Get Raspotify installer
  ansible.builtin.uri:
    url: https://dtcooper.github.io/raspotify/install.sh
    return_content: yes
  register: raspotify_installer
  when: "'raspotify' not in ansible_facts.packages"

- name: Install Raspotify
  ansible.builtin.shell:
    cmd: sh
    stdin: "{{ raspotify_installer.content }}"
  when: "'raspotify' not in ansible_facts.packages"

- name: Set username and password
  lineinfile:
    dest: /etc/raspotify/conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^#LIBRESPOT_BITRATE="160"', line: 'LIBRESPOT_BITRATE="320"' }
    - {
        regexp: '^LIBRESPOT_USERNAME=""',
        line: 'LIBRESPOT_USERNAME="{{ spotify_username }}"',
      }
    - {
        regexp: '^LIBRESPOT_PASSWORD=""',
        line: 'LIBRESPOT_PASSWORD="{{ spotify_password }}"',
      }
    - {
        regexp: '^#LIBRESPOT_DEVICE="default"',
        line: 'LIBRESPOT_DEVICE="{{ output_device }}"',
      }
  register: raspotify_config

- name: Restart Raspotify daemon
  service:
    name: raspotify
    state: restarted
  when: raspotify_config.changed
