- name: Install packages
  package:
    name:
      - tor
      - nyx
    state: latest
  tags: tor

- name: Tune tor config file
  copy:
    dest: /etc/tor/torrc
    content: |
      ORPort {{ tor_or_port }} IPv4Only
      DirPort {{ tor_dir_port }}
      ControlPort {{ tor_control_port }}
      SocksPort 0
      ExitRelay 0
      Log notice file /var/log/tor/notices.log
      HashedControlPassword {{ tor_hashed_control_password }}
      Nickname {{ tor_nickname }}
      ContactInfo {{ tor_email }}
      MyFamily {{ tor_fingerprints }}
  notify: Reload tor
  tags: tor
