- name: Install packages
  package:
    name:
      - tor
      - obfs4proxy
    state: latest
  tags: tor

- name: Tune tor config file
  template:
    src: templates/proxy_torrc.j2
    dest: /etc/tor/torrc
  notify: Reload tor
  tags: tor
