- name: Install UFW
  package:
    name:
      - ufw
    state: latest
  register: ufw_installed
  tags: ufw

- name: Reboot after UFW install
  reboot:
  when: ufw_installed.changed
  tags: ufw

- name: Check ufw service
  service:
    name: ufw
    state: started
    enabled: yes
  tags: ufw

- name: Allow ssh in UFW
  community.general.ufw:
    rule: allow
    name: OpenSSH
  tags: ufw

- name: Allow web server ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - "80"
    - "443"
  tags: ufw

- name: Allow flaresolverr ports
  community.general.ufw:
    rule: allow
    port: "8191"
  tags: ufw

# - name: Allow syncthing ports (tcp)
#   community.general.ufw:
#     rule: allow
#     proto: tcp
#     port: "{{ syncthing_listening_port }}"
#   tags: ufw
#
# - name: Allow syncthing ports (udp)
#   community.general.ufw:
#     rule: allow
#     proto: udp
#     port: "{{ item }}"
#   loop:
#     - "{{ syncthing_listening_port }}"
#     - "{{ syncthing_protocol_discovery_port }}"
#   tags: ufw
#
- name: Enable UFW
  community.general.ufw:
    state: enabled
  tags: ufw
