- name: Install UFW
  package:
    name:
      - ufw
    state: latest
  register: ufw_installed

- name: Reboot after UFW install
  reboot:
  when: ufw_installed.changed

- name: Allow ssh in UFW
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: Allow nginx in UFW
  community.general.ufw:
    rule: allow
    name: Nginx Full

- name: Allow raspotify ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - "{{ librespot_control_port }}"
    - "{{ librespot_zeroconf_port }}"

- name: Allow tor ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - "{{ tor_or_port }}"
    - "{{ tor_dir_port }}"

- name: Enable UFW
  community.general.ufw:
    state: enabled
