- name: Create docker network
  docker_network:
    name: "{{ subnet_name }}"
    ipam_config:
      - subnet: "{{ subnet_ip }}"
        gateway: "{{ subnet_gateway }}"

- name: Pull swag image
  docker_image:
    name: lscr.io/linuxserver/swag
    source: pull
    timeout: 300

- name: Init swag
  docker_container:
    name: swag
    image: lscr.io/linuxserver/swag
    capabilities:
      - net_admin
    state: started
    env:
      PUID: "{{ puid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
      URL: "{{ domain_name }}"
      VALIDATION: duckdns
      SUBDOMAINS: wildcard
      EMAIL: "{{ email }}"
      DUCKDNSTOKEN: "{{ duckdns_token }}"
      ONLY_SUBDOMAINS: "true"
    ports:
      - 443:443
      - 80:80
    volumes:
      - /etc/swag/config:/config
    restart_policy: unless-stopped
    networks:
      - name: "{{ subnet_name }}"
        ipv4_address: "{{ swag_subnet_ip }}"
