- name: Create docker network
  docker_network:
    name: "{{ docker_default_network }}"

- name: Init swag
  docker_container:
    name: swag
    image: lscr.io/linuxserver/swag
    pull: true
    networks:
      - name: "{{ docker_default_network }}"
    capabilities:
      - net_admin
    state: started
    env:
      PUID: "{{ puid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
      URL: "{{ domain_name }}"
      VALIDATION: http
      SUBDOMAINS: www,
      EMAIL: "{{ email }}"
      ONLY_SUBDOMAINS: "true"
    ports:
      - 443:443
      - 80:80
    volumes:
      - /etc/swag/config:/config
    restart_policy: unless-stopped
