# general
username: pi
puid: "1000"
guid: "1000"
timezone: Europe/Moscow
network_interface: wlan0

# docker
subnet_name: internal
subnet_ip: 172.20.0.0/16
subnet_gateway: 172.20.0.1
swag_subnet_ip: 172.20.0.2
cloudflared_subnet_ip: 172.20.0.3
pihole_subnet_ip: 172.20.0.4
diun_subnet_ip: 172.20.0.5
homer_subnet_ip: 172.20.0.6
cors_subnet_ip: 172.20.0.7

# raspotify
librespot_bitrate: "320"
librespot_control_port: "4070"
librespot_zeroconf_port: "4071"
output_device: iec958:CARD=MQA,DEV=0

# mail
smtp_host: smtp.gmail.com
smtp_port: "587"

# tor
tor_or_port: "9001"
tor_dir_port: "9030"
tor_control_port: "9051"
