# general
username: pi
puid: "1000"
guid: "1000"
timezone: Europe/Moscow
network_interface: wlan0

# docker
docker_default_network: swag

# raspotify
librespot_bitrate: "320"
librespot_control_port: "4070"
librespot_zeroconf_port: "4071"
output_device: iec958:CARD=MQA,DEV=0

# pihole
cloudflared_download_url: https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm
cloudflared_port: "5053"

# mail
smtp_server: smtp://smtp.gmail.com:587

# tor
tor_or_port: "9001"
tor_dir_port: "9030"
tor_control_port: "9051"
