- name: Restart unattended-upgrades
  service:
    name: unattended-upgrades
    state: restarted
    enabled: yes

- name: Restart swag
  docker_container:
    name: swag
    restart: yes
    env:
      PUID: "{{ puid }}"
      PGID: "{{ guid }}"
      TZ: "{{ timezone }}"
      URL: "{{ domain_name }}"
      VALIDATION: duckdns
      SUBDOMAINS: wildcard
      EMAIL: "{{ email }}"
      DUCKDNSTOKEN: "{{ duckdns_token }}"
      ONLY_SUBDOMAINS: "true"
      DOCKER_MODS: linuxserver/mods:swag-dashboard
