- name: Restart unattended-upgrades
  service:
    name: unattended-upgrades
    state: restarted
    enabled: yes

- name: Reload tor
  service:
    name: tor@default
    state: reloaded
    enabled: yes

- name: Restart swag
  docker_container:
    name: swag
    restart: yes

- name: Restart wireguard
  docker_container:
    name: wireguard
    restart: yes
